DROP DATABASE IF EXISTS 9pm_news;

CREATE DATABASE 9pm_news;

USE 9pm_news;

CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    user_name VARCHAR(255) NOT NULL,
    gender ENUM('Male', 'Female', 'Custom') NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    fb VARCHAR(255),
    instagram VARCHAR(255),
    twitter VARCHAR(255),
    picture VARCHAR(255) NOT NULL,
    verify VARCHAR(255),
    status  INT DEFAULT 1
);

CREATE TABLE categories (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
status INT DEFAULT 1
);

CREATE TABLE posts (
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
post VARCHAR(12000) NOT NULL,
date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
views INT NOT NULL DEFAULT 0,
category_id INT NOT NULL,
user_id INT NOT NULL,
thumbnail VARCHAR(255),
status INT DEFAULT 0,
PRIMARY KEY(id),
FOREIGN KEY (category_id) REFERENCES categories(id),
FOREIGN KEY (user_id) REFERENCES users(id)
);
